# Generated by Django 3.1 on 2021-05-27 17:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('type_institution', models.CharField(choices=[('fundacja', 'Fundacja'), ('organizacja pozarządowa', 'Organizacja Pozarządowa'), ('zbiórka lokalna', 'Zbiórka Lokalna')], default='fundacja', max_length=100)),
                ('categories', models.ManyToManyField(related_name='categories', to='charity.Category')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Dotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Wymagany', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Ilość')),
                ('address', models.CharField(help_text='Wymagany', max_length=255, verbose_name='Data')),
                ('phone_number', models.CharField(help_text='Wymagany', max_length=50, verbose_name='Data')),
                ('city', models.CharField(help_text='Wymagany', max_length=150, verbose_name='Data')),
                ('postcode', models.CharField(help_text='Wymagany', max_length=50, verbose_name='Kod Pocztowy')),
                ('pick_up_date', models.DateField(auto_now_add=True, help_text='Wymagany', verbose_name='Data')),
                ('pick_up_time', models.DateTimeField(auto_now_add=True, help_text='Wymagany', verbose_name='Czas')),
                ('pick_up_comment', models.TextField(blank=True, help_text='Wymagany', max_length=500, verbose_name='Komentarz')),
                ('categories', models.ManyToManyField(help_text='Wymagany', related_name='category_selection', to='charity.Category', verbose_name='Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.institution')),
                ('user', models.ForeignKey(help_text='Użytkownik', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dotation',
                'verbose_name_plural': 'Dotations',
            },
        ),
    ]
