# Generated by Django 3.1 on 2021-05-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_dotation_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotation',
            name='address',
            field=models.CharField(help_text='Wymagany', max_length=255, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='dotation',
            name='city',
            field=models.CharField(help_text='Wymagany', max_length=150, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='dotation',
            name='phone_number',
            field=models.CharField(help_text='Wymagany', max_length=50, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='dotation',
            name='pick_up_date',
            field=models.DateField(help_text='Wymagany', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='dotation',
            name='pick_up_time',
            field=models.TimeField(help_text='Wymagany', verbose_name='Czas'),
        ),
    ]
